spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbhybridlibrary?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: maki
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false